development:
  adapter: sqlite3
  database: database.db
  pool: 30

test:
  adapter: sqlite3
  database: database.db
  pool: 30

production:
  adapter: postgresql
  database: sch_database #rename this to whatever you want
  username: username
  password: password
  host: localhost
  pool: 30


  